name: "ci"

on:
  push:
    branches:
      - "**"
    tags-ignore:
      - "**"

jobs:
  ci:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: 1.17
      - uses: dominikh/staticcheck-action@v1.1.0
        with:
          install-go: false
